### ISSUE TITLE
Make `.build()` optional

### ISSUE THREAD

**Issue by andersy005** [coderepocenter/AxisUtilities#1]
While going through the documentation, I noticed that as a user I have to invoke `.build()` even when this method doesn't expect any special argument. Is it possible to abstract this away or make it optional?:

```python
from axisutilities import DailyTimeAxisBuilder
from datetime import date
from_axis = DailyTimeAxisBuilder(
    start_date=date(2019, 1, 1),
    n_interval=14
).build()
```

```python
from axisutilities import DailyTimeAxisBuilder
from datetime import date
from_axis = DailyTimeAxisBuilder(start_date=date(2019, 1, 1), n_interval=14)
```

**Comment by maboualidev** [comment]
The reason for having to call build is that I could use the same Builder and build different Axis.

Let's say:


```python
daily_axis_builder = DailyTimeAxisBuilder(start_date=date(2019, 1, 1)

daily_14days = daily_axis_builder.set_n_interval(14).build()
daily_28days = daily_axis_builder.set_n_interval(28).build()
daily_42days = daily_axis_builder.set_n_interval(42).build()
daily_365days = daily_axis_builder.set_n_interval(365).build()
```

Although you could achieve the same thing in this example, by passing the `start_date` as well.
But some of the classes get more than one parameter. or it might be some condition that you start building your axis-builder at some part of the code, but more information is available at another part of the code. In that case, you would need to pass/carry all the required parameters in all part of the code. However, using the **Builder Pattern** you add information that you have and you can modify it later.

some more example are available [here](https://axisutilities.readthedocs.io/en/latest/apireference/axisbuilders.html#axisutilities.IntervalBaseAxisBuilder).

One more thing that the following: i.e.

```Python
from_axis = DailyTimeAxisBuilder(start_date=date(2019, 1, 1), n_interval=14)
```

won't work is that the return type of `__init__` is actually `None`. To make the `from_axis` be an `Axis` object then our Builder classes need to be also `Axis` object, which they need to extend `Axis` class.

But one thing we can do. We could have `DailyTimeAxis` class in addition to `DailyTimeAxisBuilder` which works exactly as you said. I will start adding those classes in the code.

**Comment by maboualidev** [comment]
@andersy005 @matt-long 

Added necessary code to reflect this pattern. Now instead of:

```Python
daily_axis = DailyTimeAxisBuilder()\
            .set_start_date(start_date)\
            .set_end_date(end_date)\
            .build()
```
 or even:

```Python
daily_axis = DailyTimeAxisBuilder(
            start_date=start_date,
            end_date=end_date
        ).build()
```

one could issue:

```Python
daily_axis = DailyTimeAxis(
            start_date=start_date,
            end_date=end_date
        )
```

The same goes for other axis builder classes.
