### ISSUE TITLE
Adding Conda Install support

### ISSUE THREAD

**Issue by maboualidev** [coderepocenter/AxisUtilities#12]

**Comment by maboualidev** [comment]
@matt-long @andersy005 

Now you can install `AxisUtilities` from Conda. [Click Here](https://axisutilities.readthedocs.io/en/latest/introduction.html#using-conda)

**Comment by andersy005** [comment]
It might be worth adding this to conda-forge channel as to avoid dependency conflicts caused by using packages from multiple channels.
