### ISSUE TITLE
Suggestion: Expose the attributes of the timeaxis builders

### ISSUE THREAD

**Issue by andersy005** [coderepocenter/AxisUtilities#2]
According to the current docstring, one can pass arbitrary keyword arguments to the timeaxis builder:
![Screen Shot 2019-11-15 at 12 49 36 PM](https://user-images.githubusercontent.com/13301940/68971466-d05ddf80-07a6-11ea-8a71-f56a588bb8fc.png)

However, it appears that of all the kwargs, **only three of these** are used when instantiating the class.:

https://github.com/coderepocenter/AxisUtilities/blob/f13ac90d031df7d102fd6b77aaa2f3f69fef184a/axisutilities/timeaxisbuilders.py#L52-L57

I am wondering whether for clarity purposes, it makes sense to just expose these attributes in the init method i.e.

```python
def __init__(self,  start_date=None, end_date=None,  n_interval=None): 
     self.set_start_date(start_date) 
     self.set_end_date(end_date) 
     self.set_n_interval(n_interval) 
```

**Comment by maboualidev** [comment]
This pattern of having `def __init__(**kwargs)` serve two main reason.

- Allowing for future development. For example, for some cases, I had `start`, `end`, `interval`, but then decided to add `n_interval` as well. Then the user is needed to provide only three out of these fours and the fourth one could be calculated. Having the function signature to accept `**kwargs` allows me to add behavior to the function without the need to change the function signature and possibly break the codes that are using it.

- The second reason is the Inheritance. Let's say you have the following classes

```
class Parent:
  def __init__(**kwargs):
    do something with key1
    do something with key2
    do something with key3
    
    other stuff
```

and also

```
class Child
  def __init__(**kwargs)
    super().__init__(**kwargs)
    do something with key 4
    do something with key 5
    do something with key 6
```

So, now once I create an object of type Child, then the parents autotamitically handles the key 1, 2, and 3 and the Child class handles the key 4, 5, 6. 

If at some point I want to add an extra key to the Parent class, I could add it and there is no need to change any code in the Child. Automatically that extra key is also passed to the Parent.

If I had to name them, then if I make some changes to the Parent, then I need to go and change every classes that extend the Parent as well and add that extra parameter in the list. Or if someone, other than me extend the these classes, and I change the code signature, their code also breaks and they need to add those extra parameters to their `__init__` function of their class.

That's main reason. for using **kwargs. However, for some of the classes it make sense to use a fixed argument. For example, the `Axis` object accept a lower and an upper bound + dictionary. The lower and upper bound should be always provided; no matter what. So, I made them fixed.

**Comment by andersy005** [comment]
How about updating the `__init__` to

```python
def __init__(self,  start_date=None, end_date=None,  n_interval=None, **kwargs): 
     self.set_start_date(start_date) 
     self.set_end_date(end_date) 
     self.set_n_interval(n_interval) 
```
?

**Comment by andersy005** [comment]
I find 

```python
from_axis = DailyTimeAxisBuilder(start_date=date(2019, 1, 1),  
                             end_date=date(2019, 1, 8), 
                             my_kwarg_1 = None, my_kwarg_2={})
```
to provide a more pythonic interface that most users are already familiar with

**Comment by maboualidev** [comment]
I think we should leave the `Builder` classes as it is for now. Adding the named parameters could results into strange method signature as we keep extending the classes.

However, to make it more pythonic looking, we could add an extra method as follows:

```python
def daily_time_axis(arguments here):
   return DailyTimeAxisBuilder()\
            .set_start_date(date(2019, 1, 1)) \
            .set_n_interval(14) \
            .build()
```

The user could call it as like:

```Python
from_daily_axis = daly_time_axis(start_date=date(2019,1,1), n_interval=14)
```

**Comment by maboualidev** [comment]
@andersy005 
Let's keep the Builder classes as they are and open a new issue on applying these parameter changes to the equivalent methods that are recently added.
