### ISSUE TITLE
Consolidate `set_start_date()` and `set_end_date()` methods into one common method

### ISSUE THREAD

**Issue by andersy005** [coderepocenter/AxisUtilities#3]
It appears that both `set_start_date()` and `set_end_date()` are accomplishing the exact same task:

https://github.com/coderepocenter/AxisUtilities/blob/f13ac90d031df7d102fd6b77aaa2f3f69fef184a/axisutilities/timeaxisbuilders.py#L58-L72

Can we merge these two into one method in order to avoid code duplication?

**Comment by maboualidev** [comment]
Yes; Good one. I will refactor the code to address this issue.

**Comment by maboualidev** [comment]
done
